version: "3.8"
services:
    # The existing database container configuration...
    php-apache:
        container_name: laravel
        build:
            context: .
        ports:
            - "8090:80"
        volumes:
            - ./:/app
